INSERT INTO company (id, name, location, employees, industry) VALUES
    (1, 'Accenture','Helsinki','1400','Konsultointi'),
    (2, 'Capgemini','Espoo, Lappeenranta','3000','Konsultointi, Ylläpito'),
    (3, 'CGI','Helsinki, Tampere, Turku, Oulu','3200','Konsultointi'),
    (4, 'Citrus','Helsinki','40','Konsultointi, SaaS'),
    (5, 'Codemate','Helsinki, Oulu','80','Konsultointi'),
    (6, 'Codento','Helsinki','40','Konsultointi'),
    (7, 'Columbia Road','Helsinki, Stockholm','50','Konsultointi'),
    (8, 'Digia','Helsinki, Oulu, Turku, Tampere','1000','Konsultointi, SaaS'),
    (9, 'Digitalist','Helsinki, Jyväskylä, Oulu, Tampere','250','Konsultointi'),
    (10, 'Eficode','Helsinki, Tampere','200','Konsultointi'),
    (11, 'Exove','Helsinki, Oulu, Tampere','90','Konsultointi'),
    (12, 'F-Secure','Helsinki','1000','Tietoturva, SaaS'),
    (13, 'Fraktio','Helsinki','40','Konsultointi'),
    (14,'Frantic','Helsinki','100','Konsultointi'),
    (15, 'Frosmo','Helsinki, Stockholm, London','300','Tuotetalo'),
    (16, 'Futurice','Helsinki, Tampere, Berlin, London','500','Konsultointi'),
    (17, 'Geniem','Helsinki, Tampere','50','Konsultointi'),
    (18, 'Gofore','Helsinki, Jyväskylä, Tampere','400','Konsultointi'),
    (19,'HiQ','Espoo, Helsinki','300','Konsultointi'),
    (20, 'Houston Inc.','Helsinki, Turku','80','Konsultointi'),
    (21, 'Zure','Helsinki','30','Konsultointi'),
    (22, 'Leonidas','Tampere','40','Konsultointi'),
    (23, 'Netlight Consulting','Helsinki','800','Konsultointi'),
    (24, 'Nitor','Helsinki','170','Konsultointi'),
    (25, 'Nordcloud Solutions','Helsinki, Jyväskylä','250','Konsultointi'),
    (26, 'Reaktor','Helsinki, Turku, Amsterdam, New York, Tokyo','500','Konsultointi'),
    (27, 'Relex Solutions','Helsinki','450','Tuotetalo'),
    (28, 'Remedy','Espoo','150','Gaming Company'),
    (29, 'Sievo','Helsinki','50+','Tuotetalo'),
    (30, 'Siili','Helsinki, Oulu, Seinäjoki','550','Konsultointi'),
    (31, 'Sofokus','Helsinki, Turku','60','Konsultointi'),
    (32, 'Solita','Helsinki, Oulu, Tampere','650','Konsultointi'),
    (33, 'Supercell','Helsinki','170','Gaming Company'),
    (34, 'Tieto','Helsinki, Tampere, Kuopio, Oulu','14000','Konsultointi'),
    (35, 'Unikie','Helsinki, Oulu, Tampere, Turku','60','Konsultointi'),
    (36, 'UpCloud','Helsinki','20','Tuotetalo, IaaS'),
    (37, 'Vincit','Helsinki, Tampere, Turku','450','Konsultointi'),
    (38, 'Visma Solutions','Helsinki, Lappeenranta','190','Tuotetalo'),
    (39, 'Wolt','Helsinki','30','Konsultointi'),
    (40, 'Wunder','Helsinki, Turku','70','Konsultointi'),
    (41, 'Wunderdog','Helsinki','80','Konsultointi')
ON CONFLICT (id) DO UPDATE
  SET name      = excluded.name,
      location  = excluded.location,
      employees = excluded.employees,
      industry  = excluded.industry;
